export const LIMITS = {
  CART_MAX_ITEMS: 50,
  ADDRESS_MAX_PER_USER: 10,
  REVIEW_MAX_IMAGES: 5,
  FREE_SHIPPING_THRESHOLD: 500_000,
  STANDARD_SHIPPING_FEE: 30_000,
  UPLOAD_MAX_SIZE_IMAGE: 5_242_880, // 5MB
  BCRYPT_ROUNDS: 12,
  AUTO_CANCEL_PENDING_HOURS: 48,
  REVIEW_PERIOD_DAYS: 90,
  OTP_TTL_MINUTES: 60,
  RESEND_EMAIL_COOLDOWN_SECONDS: 120,
  JWT_CACHE_TTL_SECONDS: 30,
};
