export const ErrorCodes = {
  // AUTH
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_EMAIL_NOT_VERIFIED: 'AUTH_EMAIL_NOT_VERIFIED',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_ACCOUNT_INACTIVE: 'AUTH_ACCOUNT_INACTIVE',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_REFRESH_TOKEN_INVALID: 'AUTH_REFRESH_TOKEN_INVALID',
  AUTH_OTP_INVALID: 'AUTH_OTP_INVALID',
  AUTH_OTP_EXPIRED: 'AUTH_OTP_EXPIRED',
  AUTH_OTP_RESEND_TOO_SOON: 'AUTH_OTP_RESEND_TOO_SOON',

  // USER
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_EMAIL_TAKEN: 'USER_EMAIL_TAKEN',
  USER_PHONE_TAKEN: 'USER_PHONE_TAKEN',
  USER_PASSWORD_WRONG: 'USER_PASSWORD_WRONG',
  USER_PASSWORD_SAME: 'USER_PASSWORD_SAME',
  USER_CANNOT_MODIFY_SELF: 'USER_CANNOT_MODIFY_SELF',

  // ADDRESS
  ADDRESS_NOT_FOUND: 'ADDRESS_NOT_FOUND',
  ADDRESS_LIMIT_REACHED: 'ADDRESS_LIMIT_REACHED',
  ADDRESS_NOT_OWNER: 'ADDRESS_NOT_OWNER',

  // CATEGORY
  CATEGORY_NOT_FOUND: 'CATEGORY_NOT_FOUND',
  CATEGORY_SLUG_TAKEN: 'CATEGORY_SLUG_TAKEN',
  CATEGORY_PARENT_NOT_FOUND: 'CATEGORY_PARENT_NOT_FOUND',
  CATEGORY_CIRCULAR_REFERENCE: 'CATEGORY_CIRCULAR_REFERENCE',
  CATEGORY_HAS_CHILDREN: 'CATEGORY_HAS_CHILDREN',
  CATEGORY_HAS_PRODUCTS: 'CATEGORY_HAS_PRODUCTS',

  // PRODUCT
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_SLUG_TAKEN: 'PRODUCT_SLUG_TAKEN',
  PRODUCT_VARIANT_NOT_FOUND: 'PRODUCT_VARIANT_NOT_FOUND',
  PRODUCT_OUT_OF_STOCK: 'PRODUCT_OUT_OF_STOCK',
  PRODUCT_INSUFFICIENT_STOCK: 'PRODUCT_INSUFFICIENT_STOCK',
  PRODUCT_INACTIVE: 'PRODUCT_INACTIVE',

  // CART
  CART_ITEM_NOT_FOUND: 'CART_ITEM_NOT_FOUND',
  CART_MAX_ITEMS_REACHED: 'CART_MAX_ITEMS_REACHED',
  CART_EMPTY: 'CART_EMPTY',

  // COUPON
  COUPON_NOT_FOUND: 'COUPON_NOT_FOUND',
  COUPON_INACTIVE: 'COUPON_INACTIVE',
  COUPON_EXPIRED: 'COUPON_EXPIRED',
  COUPON_NOT_YET_ACTIVE: 'COUPON_NOT_YET_ACTIVE',
  COUPON_USAGE_LIMIT_REACHED: 'COUPON_USAGE_LIMIT_REACHED',
  COUPON_USER_LIMIT_REACHED: 'COUPON_USER_LIMIT_REACHED',
  COUPON_MIN_ORDER_NOT_MET: 'COUPON_MIN_ORDER_NOT_MET',
  COUPON_ALREADY_APPLIED: 'COUPON_ALREADY_APPLIED',

  // ORDER
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  ORDER_NOT_OWNER: 'ORDER_NOT_OWNER',
  ORDER_CANNOT_CANCEL: 'ORDER_CANNOT_CANCEL',
  ORDER_ALREADY_PAID: 'ORDER_ALREADY_PAID',
  ORDER_INVALID_STATUS_TRANSITION: 'ORDER_INVALID_STATUS_TRANSITION',

  // REVIEW
  REVIEW_NOT_FOUND: 'REVIEW_NOT_FOUND',
  REVIEW_ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
  REVIEW_ORDER_NOT_DELIVERED: 'REVIEW_ORDER_NOT_DELIVERED',
  REVIEW_PERIOD_EXPIRED: 'REVIEW_PERIOD_EXPIRED',
  REVIEW_NOT_OWNER: 'REVIEW_NOT_OWNER',

  // UPLOAD
  UPLOAD_FILE_TOO_LARGE: 'UPLOAD_FILE_TOO_LARGE',
  UPLOAD_INVALID_TYPE: 'UPLOAD_INVALID_TYPE',
  UPLOAD_FAILED: 'UPLOAD_FAILED',

  // BANNER
  BANNER_NOT_FOUND: 'BANNER_NOT_FOUND',

  // NOTIFICATION
  NOTIFICATION_NOT_FOUND: 'NOTIFICATION_NOT_FOUND',
  NOTIFICATION_NOT_OWNER: 'NOTIFICATION_NOT_OWNER',

  // VALIDATION
  VALIDATION_INVALID_OBJECT_ID: 'VALIDATION_INVALID_OBJECT_ID',
  VALIDATION_FAILED: 'VALIDATION_FAILED',

  // SYSTEM
  SYS_INTERNAL_ERROR: 'SYS_INTERNAL_ERROR',
  SYS_SERVICE_UNAVAILABLE: 'SYS_SERVICE_UNAVAILABLE',
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
